### ISSUE TITLE
Java 9 build error: "error: package javax.rmi.CORBA is not visible"

### ISSUE THREAD

**Issue by mkotsbak** [JacORB/JacORB#214]
JacORB is not building with Oracle Java 9:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.1:jar (default) on project jacorb: MavenReportException: Error while creating archive: 
[ERROR] Exit code: 1 - /home/marius/tmp/jacorb-3.9/core/src/main/java/org/jacorb/util/ValueHandler.java:3: error: package javax.rmi.CORBA is not visible
[ERROR] import javax.rmi.CORBA.ValueHandlerMultiFormat;
[ERROR]                 ^
[ERROR]   (package javax.rmi.CORBA is declared in module java.corba, which is not in the module graph)
[ERROR] /home/marius/tmp/jacorb-3.9/core/src/main/java/org/jacorb/orb/Reference.java:26: error: package javax.rmi.CORBA is not visible
[ERROR]     extends javax.rmi.CORBA.Stub implements java.rmi.Remote
[ERROR]                      ^
[ERROR]   (package javax.rmi.CORBA is declared in module java.corba, which is not in the module graph)
[ERROR] /home/marius/tmp/jacorb-3.9/core/src/main/java/org/jacorb/orb/rmi/PortableRemoteObjectDelegateImpl.java:28: error: package javax.rmi.CORBA is not visible
```

The CORBA module ("java.corba") probably needs to be specified that is needed for this project. See https://www.oracle.com/corporate/features/understanding-java-9-modules.html

**Comment by rnc** [comment]
Currently Java 9 support is not there although there has been some discussions on the mailing list. Contributions welcome!

**Comment by mkotsbak** [comment]
I tried adding
```
                    <compilerArgs>
                      <arg>--add-modules</arg>
                      <arg>java.corba</arg>
                    </compilerArgs>
```

to core/pom.xml. Seemed it solved some issues, but I got:

Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project jacorb: Fatal error compiling: option --add-modules not allowed with target 1.6 -> [Help 1]

Seems it is impossible to support both 1.9 and 1.6. But anyway 1.6 is EOL so why support it?

**Comment by mkotsbak** [comment]
Well, it does not work with target 1.8 either, so in the worst case you need to make separate artifacts for Java 9+...

**Comment by david-gibbs-ig** [comment]
@rnc Hi if you look here https://openjdk.java.net/jeps/320 we see that javax.rmi packages are omitted from Java 11 distributions. Would the terms of the Open JDK license allow us to make a small independent distribution of only the required packages on which JacORB would then depend ? I think this would be a good stopgap while hoping for a suitable EE4J distribution to become available. I think the terms would allow this and having such a dependency can I think avoid entangling the JacORB and OpenJDK licenses. If this sounds sensible to you I will work on it.

**Comment by david-gibbs-ig** [comment]
Hi for the benefit of those interested in this issue please see the following note on running in Java 11. 
This is not yet peer reviewed (by me) :-)
http://lists.spline.inf.fu-berlin.de/pipermail/jacorb-developer/2018-July/000927.html

**Comment by rnc** [comment]
This should be resolved by #314
